name: Update JSON Data
on:
  repository_dispatch:
    types: [update_data]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update JSON file
        run: |
          echo '${{ github.event.client_payload.data }}' > manual_links.json
          
      - name: Commit and Push
        run: |
          git config --global user.name "Admin Dashboard"
          git config --global user.email "admin@dashboard.com"
          git add manual_links.json
          git commit -m "Update content from Admin UI"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
